services:
  # FastAPI Backend Service
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: scomp_api
    env_file: ./config/.env
    environment:
      # Database Configuration (Remote TacticalData)
      RUN_MIGRATIONS: "true"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      
      # SportsDynamics API
      SPORTSDYNAMICS_API_URL: https://api-v2.sportsdynamics.eu/graphql
    ports:
      - "8001:8001"
    depends_on:
      - redis
    networks:
      - scomp_network
    volumes:
      - ./backend:/app/backend
      - ./start:/app/start
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: scomp_redis
    networks:
      - scomp_network
    restart: unless-stopped

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: scomp_worker
    env_file: ./config/.env
    environment:
      SPORTSDYNAMICS_API_URL: https://api-v2.sportsdynamics.eu/graphql
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: ["celery -A src.tasks.scrape_tasks:app worker --loglevel=INFO --concurrency=1"]
    depends_on:
      - redis
    networks:
      - scomp_network
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped

  beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: scomp_beat
    env_file: ./config/.env
    environment:
      SPORTSDYNAMICS_API_URL: https://api-v2.sportsdynamics.eu/graphql
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: ["celery -A src.tasks.beat:app beat --loglevel=INFO"]
    depends_on:
      - redis
    networks:
      - scomp_network
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped

  # React Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: scomp_frontend
    ports:
      - "3002:3002"
    depends_on:
      - api
    networks:
      - scomp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:3002/"]
      interval: 10s
      timeout: 5s
      retries: 5

# Networks (service communication)
networks:
  scomp_network:
    driver: bridge

