"""Add logo_url column to teams table

Revision ID: 044_add_logo_url_to_teams
Revises: 043_add_player_teams_tracking
Create Date: 2026-09-10 15:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044_add_logo_url_to_teams'
down_revision = '043_add_player_teams_tracking'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'logo_url')
    # ### end Alembic commands ###
