"""Create the independent STATSport PhysicalData schema."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "20260922_000000"
down_revision = None
branch_labels = ("physical_data",)
depends_on = None
SCHEMA = "public"


def upgrade() -> None:
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")
    op.create_table("squads", sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("external_id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("name", sa.Text()), sa.Column("raw_data", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("external_id"), schema=SCHEMA)
    op.create_table("players", sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("identity_key", sa.Text(), nullable=False), sa.Column("display_name", sa.Text()), sa.Column("first_name", sa.Text()), sa.Column("last_name", sa.Text()), sa.Column("primary_position", sa.Text()), sa.Column("secondary_position", sa.Text()), sa.Column("active_squad_name", sa.Text()), sa.Column("player_details", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("identity_key"), schema=SCHEMA)
    op.create_table("sessions", sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("activity_id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("activity_name", sa.Text()), sa.Column("share_date", sa.DateTime(timezone=True), nullable=False), sa.Column("squad_id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("session_date", sa.DateTime(timezone=True), nullable=False), sa.Column("start_time", sa.DateTime(timezone=True)), sa.Column("end_time", sa.DateTime(timezone=True)), sa.Column("session_type", sa.Text()), sa.Column("raw_data", postgresql.JSONB(), nullable=False), sa.Column("response_hash", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.ForeignKeyConstraint(["squad_id"], [f"{SCHEMA}.squads.id"], ondelete="RESTRICT"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("activity_id"), schema=SCHEMA)
    op.create_table("session_players", sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("session_id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("player_id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("source_id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("raw_data_id", postgresql.UUID(as_uuid=False)), sa.Column("player_details", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.ForeignKeyConstraint(["player_id"], [f"{SCHEMA}.players.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["session_id"], [f"{SCHEMA}.sessions.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("session_id", "player_id"), sa.UniqueConstraint("session_id", "source_id"), schema=SCHEMA)
    op.create_table("drill_metadata", sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("session_id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("signature", sa.Text(), nullable=False), sa.Column("drill_name", sa.Text()), sa.Column("primary_label", sa.Text()), sa.Column("secondary_label", sa.Text()), sa.Column("tertiary_label", sa.Text()), sa.Column("session_type", sa.Text()), sa.ForeignKeyConstraint(["session_id"], [f"{SCHEMA}.sessions.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("session_id", "signature"), schema=SCHEMA)
    op.create_table("drills", sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("session_player_id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("drill_metadata_id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("source_id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("session_player_data_id", postgresql.UUID(as_uuid=False)), sa.Column("start_time", sa.DateTime(timezone=True)), sa.Column("end_time", sa.DateTime(timezone=True)), sa.Column("free_text", sa.Text()), sa.Column("metrics", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("raw_data", postgresql.JSONB(), nullable=False), sa.ForeignKeyConstraint(["drill_metadata_id"], [f"{SCHEMA}.drill_metadata.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["session_player_id"], [f"{SCHEMA}.session_players.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("session_player_id", "source_id"), schema=SCHEMA)
    op.create_table("api_snapshots", sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False), sa.Column("endpoint", sa.Text(), nullable=False), sa.Column("request_payload", postgresql.JSONB()), sa.Column("response_payload", postgresql.JSONB(), nullable=False), sa.Column("http_status", sa.Integer(), nullable=False), sa.Column("api_version", sa.Text(), nullable=False), sa.Column("response_hash", sa.Text(), nullable=False), sa.Column("received_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.PrimaryKeyConstraint("id"), schema=SCHEMA)
    for table, column in (("sessions", "share_date"), ("sessions", "squad_id"), ("session_players", "session_id"), ("session_players", "player_id"), ("drill_metadata", "session_id"), ("drills", "session_player_id"), ("drills", "drill_metadata_id"), ("api_snapshots", "response_hash")):
        op.create_index(f"ix_{table}_{column}", table, [column], schema=SCHEMA)
    op.create_index("ix_drills_metrics", "drills", ["metrics"], schema=SCHEMA, postgresql_using="gin")


def downgrade() -> None:
    op.drop_schema(SCHEMA, cascade=True)
