"""Add Player, LineupTeam, and LineupPlayer tables

Revision ID: b15e00574e6a
Revises: da4712332872
Create Date: 2026-08-14 14:47:10.153631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b15e00574e6a'
down_revision: Union[str, None] = 'da4712332872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('players', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('players', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('players', 'usage_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index('ix_players_team_id', table_name='players')
    op.drop_constraint('players_team_id_fkey', 'players', type_='foreignkey')
    op.drop_column('players', 'jersey_number')
    op.drop_column('players', 'raw_data')
    op.drop_column('players', 'team_id')
    op.drop_column('players', 'provider_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('provider_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('team_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('jersey_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('players_team_id_fkey', 'players', 'teams', ['team_id'], ['id'])
    op.create_index('ix_players_team_id', 'players', ['team_id'], unique=False)
    op.alter_column('players', 'usage_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('players', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('players', 'last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('players', 'first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
