"""Add player profile fields to players table

Revision ID: d9e1f2a3b4c5
Revises: c8f9d2e3a1b2
Create Date: 2026-08-15 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e1f2a3b4c5'
down_revision: Union[str, None] = 'c8f9d2e3a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('photo', sa.String(length=500), nullable=True))
    op.add_column('players', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('players', sa.Column('current_team_id', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('current_team_brand', sa.String(length=255), nullable=True))
    op.add_column('players', sa.Column('current_national_team_id', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('current_national_team_brand', sa.String(length=255), nullable=True))
    op.add_column('players', sa.Column('nationalities', sa.JSON(), nullable=True))
    op.add_column('players', sa.Column('positions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'positions')
    op.drop_column('players', 'nationalities')
    op.drop_column('players', 'current_national_team_brand')
    op.drop_column('players', 'current_national_team_id')
    op.drop_column('players', 'current_team_brand')
    op.drop_column('players', 'current_team_id')
    op.drop_column('players', 'birthdate')
    op.drop_column('players', 'age')
    op.drop_column('players', 'photo')
    # ### end Alembic commands ###
